version: '3.3'
services:
  joomla:
    image: joomla:3.6.2-apache
    links:
      - wordpressdb
    ports:
      - "8080:80"
    environment:
      - JOOMLA_DB_HOST=wordpressdb:3306
      - JOOMLA_DB_PASSWORD=secret
    volumes:
      - ./code:/var/www/html

  wordpressdb:
    container_name: wordpressdb
    image: mariadb:latest
    restart: always
    volumes:
      - "/opt/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress